name: Bug Report & Enhancement Request
about: Help us improve our docs by reporting content issues or suggesting enhancements.
title: '[Content Issue] A concise title for the content issue or enhancement'
labels:
  - bug
  - enhancement

body:
  - type: input
    id: describe-issue
    attributes:
      label: 'Describe the issue or enhancement'
      description:
        'A clear and concise description of the content issue or the enhancement you are suggesting. Yes, we know you
        could be doing something more fun, but here you are.'
      placeholder: 'The issue or enhancement is...'
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: 'Location of the issue'
      description:
        'Provide the URL or path to the page where the issue exists. Because scavenger hunts are only fun in real life.'
      placeholder: 'URL or path...'
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: 'To Reproduce (if applicable)'
      description:
        "Steps to reproduce the behavior (if it's an issue). Pretend we're five years old and need everything spelled
        out."
      placeholder: "1. Go to '...'\n2. Read '....'\n3. Notice the problem"
    validations:
      required: false

  - type: input
    id: expected-behavior
    attributes:
      label: 'Expected behavior or improvement'
      description:
        'A clear and concise description of what you expected to see or how you think it can be improved. Because
        reality is often disappointing.'
      placeholder: 'I expected to see...'
    validations:
      required: true

  - type: input
    id: screenshots
    attributes:
      label: 'Screenshots or Relevant Links'
      description:
        'If applicable, add screenshots or links to help explain your problem or suggestion. Because a picture is worth
        a thousand facepalms.'
      placeholder: 'Add screenshots or links...'
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description:
        'Add any other context about the problem or suggestion here. The more you tell us, the less we have to guess.
        And, so you know, we are TERRIBLE guessers.'
      placeholder: 'Additional context...'
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        --- 
        *We might roll our eyes, but we genuinely appreciate your help in making our docs better. Thanks for your keen observation and suggestions!*
