name: Improvement
description: Help us improve our docs by reporting content issues or suggesting enhancements.
title: '[Content Issue] A concise title for the content issue or enhancement'
labels:
  - bug
  - enhancement

body:
  - type: textarea
    id: describe-issue
    attributes:
      label: 'Describe the improvement'
      description:
        'A clear and concise description of the content issue or improvement you are suggesting. Yes, we know you could
        be doing something more fun, but here you are.'
      placeholder: 'The improvement is...'
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: 'Location of the improvement'
      description:
        'Provide the URL or path to the page where we can make the improvement. Because scavenger hunts are only fun in
        real life.'
      placeholder: 'URL or path...'
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context (optional)'
      description:
        'Add any other context about the problem or suggestion here. Feel free to add screenshots, recordings, your
        favorite recipe for flan, etc. The more you tell us, the less we have to guess. And, so you know, we are
        TERRIBLE guessers.'
      placeholder: 'Additional context...'
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        --- 
        *We might roll our eyes, but we genuinely appreciate your help in making our docs better. Thanks for your keen observation and suggestions!*
