name: Missing Feature Request
description: Suggest a missing feature or enhancement for our documentation.
title: '[Missing Feature] A concise title for the feature'
labels:
  - missing

body:
  - type: input
    id: related-problem
    attributes:
      label: 'Is your feature request related to a problem? Please describe.'
      description:
        "A clear and concise description of what the problem is. Ex. I'm always frustrated when I can't find [...]"
      placeholder: 'The problem is...'
    validations:
      required: true

  - type: input
    id: describe-solution
    attributes:
      label: "Describe the content or feature you'd like"
      description: 'A clear and concise description of what you want to happen. Because obviously, we missed it.'
      placeholder: 'I would like to see...'
    validations:
      required: true

  - type: input
    id: describe-alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description:
        "A clear and concise description of any alternative solutions or features you've considered. Maybe we got
        something right by accident."
      placeholder: "I've considered the following alternatives..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: 'Additional context'
      description: 'Add any other context or examples about the feature request here. The more, the merrier.'
      placeholder: 'Additional context...'
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        *We can't promise it'll make the next release, but hey, dreaming is free! Thanks for your suggestion. Either way, we'll be in touch.*
